// Generated file. Do not edit manually.
class CountriesData {
  static const List<Map<String, String>> countries = [
    {
      'name': 'Afghanistan',
      'code': 'AF',
      'currency': 'AFN',
      'flag': '🇦🇫',
    },
    {
      'name': 'Afrique du Sud',
      'code': 'ZA',
      'currency': 'ZAR',
      'flag': '🇿🇦',
    },
    {
      'name': 'Ahvenanmaa',
      'code': 'AX',
      'currency': 'EUR',
      'flag': '🇦🇽',
    },
    {
      'name': 'Albanie',
      'code': 'AL',
      'currency': 'ALL',
      'flag': '🇦🇱',
    },
    {
      'name': 'Algérie',
      'code': 'DZ',
      'currency': 'DZD',
      'flag': '🇩🇿',
    },
    {
      'name': 'Allemagne',
      'code': 'DE',
      'currency': 'EUR',
      'flag': '🇩🇪',
    },
    {
      'name': 'Andorre',
      'code': 'AD',
      'currency': 'EUR',
      'flag': '🇦🇩',
    },
    {
      'name': 'Angola',
      'code': 'AO',
      'currency': 'AOA',
      'flag': '🇦🇴',
    },
    {
      'name': 'Anguilla',
      'code': 'AI',
      'currency': 'XCD',
      'flag': '🇦🇮',
    },
    {
      'name': 'Antarctique',
      'code': 'AQ',
      'currency': '',
      'flag': '🇦🇶',
    },
    {
      'name': 'Antigua-et-Barbuda',
      'code': 'AG',
      'currency': 'XCD',
      'flag': '🇦🇬',
    },
    {
      'name': 'Arabie Saoudite',
      'code': 'SA',
      'currency': 'SAR',
      'flag': '🇸🇦',
    },
    {
      'name': 'Argentine',
      'code': 'AR',
      'currency': 'ARS',
      'flag': '🇦🇷',
    },
    {
      'name': 'Arménie',
      'code': 'AM',
      'currency': 'AMD',
      'flag': '🇦🇲',
    },
    {
      'name': 'Aruba',
      'code': 'AW',
      'currency': 'AWG',
      'flag': '🇦🇼',
    },
    {
      'name': 'Australie',
      'code': 'AU',
      'currency': 'AUD',
      'flag': '🇦🇺',
    },
    {
      'name': 'Autriche',
      'code': 'AT',
      'currency': 'EUR',
      'flag': '🇦🇹',
    },
    {
      'name': 'Azerbaïdjan',
      'code': 'AZ',
      'currency': 'AZN',
      'flag': '🇦🇿',
    },
    {
      'name': 'Bahamas',
      'code': 'BS',
      'currency': 'BSD',
      'flag': '🇧🇸',
    },
    {
      'name': 'Bahreïn',
      'code': 'BH',
      'currency': 'BHD',
      'flag': '🇧🇭',
    },
    {
      'name': 'Bangladesh',
      'code': 'BD',
      'currency': 'BDT',
      'flag': '🇧🇩',
    },
    {
      'name': 'Barbade',
      'code': 'BB',
      'currency': 'BBD',
      'flag': '🇧🇧',
    },
    {
      'name': 'Belgique',
      'code': 'BE',
      'currency': 'EUR',
      'flag': '🇧🇪',
    },
    {
      'name': 'Belize',
      'code': 'BZ',
      'currency': 'BZD',
      'flag': '🇧🇿',
    },
    {
      'name': 'Bermudes',
      'code': 'BM',
      'currency': 'BMD',
      'flag': '🇧🇲',
    },
    {
      'name': 'Bhoutan',
      'code': 'BT',
      'currency': 'BTN',
      'flag': '🇧🇹',
    },
    {
      'name': 'Birmanie',
      'code': 'MM',
      'currency': 'MMK',
      'flag': '🇲🇲',
    },
    {
      'name': 'Biélorussie',
      'code': 'BY',
      'currency': 'BYN',
      'flag': '🇧🇾',
    },
    {
      'name': 'Bolivie',
      'code': 'BO',
      'currency': 'BOB',
      'flag': '🇧🇴',
    },
    {
      'name': 'Bosnie-Herzégovine',
      'code': 'BA',
      'currency': 'BAM',
      'flag': '🇧🇦',
    },
    {
      'name': 'Botswana',
      'code': 'BW',
      'currency': 'BWP',
      'flag': '🇧🇼',
    },
    {
      'name': 'Brunei',
      'code': 'BN',
      'currency': 'BND',
      'flag': '🇧🇳',
    },
    {
      'name': 'Brésil',
      'code': 'BR',
      'currency': 'BRL',
      'flag': '🇧🇷',
    },
    {
      'name': 'Bulgarie',
      'code': 'BG',
      'currency': 'BGN',
      'flag': '🇧🇬',
    },
    {
      'name': 'Burkina Faso',
      'code': 'BF',
      'currency': 'XOF',
      'flag': '🇧🇫',
    },
    {
      'name': 'Burundi',
      'code': 'BI',
      'currency': 'BIF',
      'flag': '🇧🇮',
    },
    {
      'name': 'Bénin',
      'code': 'BJ',
      'currency': 'XOF',
      'flag': '🇧🇯',
    },
    {
      'name': 'Cambodge',
      'code': 'KH',
      'currency': 'KHR',
      'flag': '🇰🇭',
    },
    {
      'name': 'Cameroun',
      'code': 'CM',
      'currency': 'XAF',
      'flag': '🇨🇲',
    },
    {
      'name': 'Canada',
      'code': 'CA',
      'currency': 'CAD',
      'flag': '🇨🇦',
    },
    {
      'name': 'Chili',
      'code': 'CL',
      'currency': 'CLP',
      'flag': '🇨🇱',
    },
    {
      'name': 'Chine',
      'code': 'CN',
      'currency': 'CNY',
      'flag': '🇨🇳',
    },
    {
      'name': 'Chypre',
      'code': 'CY',
      'currency': 'EUR',
      'flag': '🇨🇾',
    },
    {
      'name': 'Cité du Vatican',
      'code': 'VA',
      'currency': 'EUR',
      'flag': '🇻🇦',
    },
    {
      'name': 'Colombie',
      'code': 'CO',
      'currency': 'COP',
      'flag': '🇨🇴',
    },
    {
      'name': 'Comores',
      'code': 'KM',
      'currency': 'KMF',
      'flag': '🇰🇲',
    },
    {
      'name': 'Congo',
      'code': 'CG',
      'currency': 'XAF',
      'flag': '🇨🇬',
    },
    {
      'name': 'Congo (Rép. dém.)',
      'code': 'CD',
      'currency': 'CDF',
      'flag': '🇨🇩',
    },
    {
      'name': 'Corée du Nord',
      'code': 'KP',
      'currency': 'KPW',
      'flag': '🇰🇵',
    },
    {
      'name': 'Corée du Sud',
      'code': 'KR',
      'currency': 'KRW',
      'flag': '🇰🇷',
    },
    {
      'name': 'Costa Rica',
      'code': 'CR',
      'currency': 'CRC',
      'flag': '🇨🇷',
    },
    {
      'name': 'Croatie',
      'code': 'HR',
      'currency': 'EUR',
      'flag': '🇭🇷',
    },
    {
      'name': 'Cuba',
      'code': 'CU',
      'currency': 'CUC',
      'flag': '🇨🇺',
    },
    {
      'name': 'Curaçao',
      'code': 'CW',
      'currency': 'ANG',
      'flag': '🇨🇼',
    },
    {
      'name': 'Côte d\'Ivoire',
      'code': 'CI',
      'currency': 'XOF',
      'flag': '🇨🇮',
    },
    {
      'name': 'Danemark',
      'code': 'DK',
      'currency': 'DKK',
      'flag': '🇩🇰',
    },
    {
      'name': 'Djibouti',
      'code': 'DJ',
      'currency': 'DJF',
      'flag': '🇩🇯',
    },
    {
      'name': 'Dominique',
      'code': 'DM',
      'currency': 'XCD',
      'flag': '🇩🇲',
    },
    {
      'name': 'Espagne',
      'code': 'ES',
      'currency': 'EUR',
      'flag': '🇪🇸',
    },
    {
      'name': 'Estonie',
      'code': 'EE',
      'currency': 'EUR',
      'flag': '🇪🇪',
    },
    {
      'name': 'Eswatini',
      'code': 'SZ',
      'currency': 'SZL',
      'flag': '🇸🇿',
    },
    {
      'name': 'Fidji',
      'code': 'FJ',
      'currency': 'FJD',
      'flag': '🇫🇯',
    },
    {
      'name': 'Finlande',
      'code': 'FI',
      'currency': 'EUR',
      'flag': '🇫🇮',
    },
    {
      'name': 'France',
      'code': 'FR',
      'currency': 'EUR',
      'flag': '🇫🇷',
    },
    {
      'name': 'Gabon',
      'code': 'GA',
      'currency': 'XAF',
      'flag': '🇬🇦',
    },
    {
      'name': 'Gambie',
      'code': 'GM',
      'currency': 'GMD',
      'flag': '🇬🇲',
    },
    {
      'name': 'Ghana',
      'code': 'GH',
      'currency': 'GHS',
      'flag': '🇬🇭',
    },
    {
      'name': 'Gibraltar',
      'code': 'GI',
      'currency': 'GIP',
      'flag': '🇬🇮',
    },
    {
      'name': 'Grenade',
      'code': 'GD',
      'currency': 'XCD',
      'flag': '🇬🇩',
    },
    {
      'name': 'Groenland',
      'code': 'GL',
      'currency': 'DKK',
      'flag': '🇬🇱',
    },
    {
      'name': 'Grèce',
      'code': 'GR',
      'currency': 'EUR',
      'flag': '🇬🇷',
    },
    {
      'name': 'Guadeloupe',
      'code': 'GP',
      'currency': 'EUR',
      'flag': '🇬🇵',
    },
    {
      'name': 'Guam',
      'code': 'GU',
      'currency': 'USD',
      'flag': '🇬🇺',
    },
    {
      'name': 'Guatemala',
      'code': 'GT',
      'currency': 'GTQ',
      'flag': '🇬🇹',
    },
    {
      'name': 'Guernesey',
      'code': 'GG',
      'currency': 'GBP',
      'flag': '🇬🇬',
    },
    {
      'name': 'Guinée',
      'code': 'GN',
      'currency': 'GNF',
      'flag': '🇬🇳',
    },
    {
      'name': 'Guinée équatoriale',
      'code': 'GQ',
      'currency': 'XAF',
      'flag': '🇬🇶',
    },
    {
      'name': 'Guinée-Bissau',
      'code': 'GW',
      'currency': 'XOF',
      'flag': '🇬🇼',
    },
    {
      'name': 'Guyana',
      'code': 'GY',
      'currency': 'GYD',
      'flag': '🇬🇾',
    },
    {
      'name': 'Guyane',
      'code': 'GF',
      'currency': 'EUR',
      'flag': '🇬🇫',
    },
    {
      'name': 'Géorgie',
      'code': 'GE',
      'currency': 'GEL',
      'flag': '🇬🇪',
    },
    {
      'name': 'Géorgie du Sud-et-les Îles Sandwich du Sud',
      'code': 'GS',
      'currency': 'SHP',
      'flag': '🇬🇸',
    },
    {
      'name': 'Haïti',
      'code': 'HT',
      'currency': 'HTG',
      'flag': '🇭🇹',
    },
    {
      'name': 'Honduras',
      'code': 'HN',
      'currency': 'HNL',
      'flag': '🇭🇳',
    },
    {
      'name': 'Hong Kong',
      'code': 'HK',
      'currency': 'HKD',
      'flag': '🇭🇰',
    },
    {
      'name': 'Hongrie',
      'code': 'HU',
      'currency': 'HUF',
      'flag': '🇭🇺',
    },
    {
      'name': 'Inde',
      'code': 'IN',
      'currency': 'INR',
      'flag': '🇮🇳',
    },
    {
      'name': 'Indonésie',
      'code': 'ID',
      'currency': 'IDR',
      'flag': '🇮🇩',
    },
    {
      'name': 'Irak',
      'code': 'IQ',
      'currency': 'IQD',
      'flag': '🇮🇶',
    },
    {
      'name': 'Iran',
      'code': 'IR',
      'currency': 'IRR',
      'flag': '🇮🇷',
    },
    {
      'name': 'Irlande',
      'code': 'IE',
      'currency': 'EUR',
      'flag': '🇮🇪',
    },
    {
      'name': 'Islande',
      'code': 'IS',
      'currency': 'ISK',
      'flag': '🇮🇸',
    },
    {
      'name': 'Israël',
      'code': 'IL',
      'currency': 'ILS',
      'flag': '🇮🇱',
    },
    {
      'name': 'Italie',
      'code': 'IT',
      'currency': 'EUR',
      'flag': '🇮🇹',
    },
    {
      'name': 'Jamaïque',
      'code': 'JM',
      'currency': 'JMD',
      'flag': '🇯🇲',
    },
    {
      'name': 'Japon',
      'code': 'JP',
      'currency': 'JPY',
      'flag': '🇯🇵',
    },
    {
      'name': 'Jersey',
      'code': 'JE',
      'currency': 'GBP',
      'flag': '🇯🇪',
    },
    {
      'name': 'Jordanie',
      'code': 'JO',
      'currency': 'JOD',
      'flag': '🇯🇴',
    },
    {
      'name': 'Kazakhstan',
      'code': 'KZ',
      'currency': 'KZT',
      'flag': '🇰🇿',
    },
    {
      'name': 'Kenya',
      'code': 'KE',
      'currency': 'KES',
      'flag': '🇰🇪',
    },
    {
      'name': 'Kirghizistan',
      'code': 'KG',
      'currency': 'KGS',
      'flag': '🇰🇬',
    },
    {
      'name': 'Kiribati',
      'code': 'KI',
      'currency': 'AUD',
      'flag': '🇰🇮',
    },
    {
      'name': 'Kosovo',
      'code': 'XK',
      'currency': 'EUR',
      'flag': '🇽🇰',
    },
    {
      'name': 'Koweït',
      'code': 'KW',
      'currency': 'KWD',
      'flag': '🇰🇼',
    },
    {
      'name': 'Laos',
      'code': 'LA',
      'currency': 'LAK',
      'flag': '🇱🇦',
    },
    {
      'name': 'Lesotho',
      'code': 'LS',
      'currency': 'LSL',
      'flag': '🇱🇸',
    },
    {
      'name': 'Lettonie',
      'code': 'LV',
      'currency': 'EUR',
      'flag': '🇱🇻',
    },
    {
      'name': 'Liban',
      'code': 'LB',
      'currency': 'LBP',
      'flag': '🇱🇧',
    },
    {
      'name': 'Liberia',
      'code': 'LR',
      'currency': 'LRD',
      'flag': '🇱🇷',
    },
    {
      'name': 'Libye',
      'code': 'LY',
      'currency': 'LYD',
      'flag': '🇱🇾',
    },
    {
      'name': 'Liechtenstein',
      'code': 'LI',
      'currency': 'CHF',
      'flag': '🇱🇮',
    },
    {
      'name': 'Lituanie',
      'code': 'LT',
      'currency': 'EUR',
      'flag': '🇱🇹',
    },
    {
      'name': 'Luxembourg',
      'code': 'LU',
      'currency': 'EUR',
      'flag': '🇱🇺',
    },
    {
      'name': 'Macao',
      'code': 'MO',
      'currency': 'MOP',
      'flag': '🇲🇴',
    },
    {
      'name': 'Macédoine du Nord',
      'code': 'MK',
      'currency': 'MKD',
      'flag': '🇲🇰',
    },
    {
      'name': 'Madagascar',
      'code': 'MG',
      'currency': 'MGA',
      'flag': '🇲🇬',
    },
    {
      'name': 'Malaisie',
      'code': 'MY',
      'currency': 'MYR',
      'flag': '🇲🇾',
    },
    {
      'name': 'Malawi',
      'code': 'MW',
      'currency': 'MWK',
      'flag': '🇲🇼',
    },
    {
      'name': 'Maldives',
      'code': 'MV',
      'currency': 'MVR',
      'flag': '🇲🇻',
    },
    {
      'name': 'Mali',
      'code': 'ML',
      'currency': 'XOF',
      'flag': '🇲🇱',
    },
    {
      'name': 'Malte',
      'code': 'MT',
      'currency': 'EUR',
      'flag': '🇲🇹',
    },
    {
      'name': 'Maroc',
      'code': 'MA',
      'currency': 'MAD',
      'flag': '🇲🇦',
    },
    {
      'name': 'Martinique',
      'code': 'MQ',
      'currency': 'EUR',
      'flag': '🇲🇶',
    },
    {
      'name': 'Mauritanie',
      'code': 'MR',
      'currency': 'MRU',
      'flag': '🇲🇷',
    },
    {
      'name': 'Mayotte',
      'code': 'YT',
      'currency': 'EUR',
      'flag': '🇾🇹',
    },
    {
      'name': 'Mexique',
      'code': 'MX',
      'currency': 'MXN',
      'flag': '🇲🇽',
    },
    {
      'name': 'Micronésie',
      'code': 'FM',
      'currency': '',
      'flag': '🇫🇲',
    },
    {
      'name': 'Moldavie',
      'code': 'MD',
      'currency': 'MDL',
      'flag': '🇲🇩',
    },
    {
      'name': 'Monaco',
      'code': 'MC',
      'currency': 'EUR',
      'flag': '🇲🇨',
    },
    {
      'name': 'Mongolie',
      'code': 'MN',
      'currency': 'MNT',
      'flag': '🇲🇳',
    },
    {
      'name': 'Montserrat',
      'code': 'MS',
      'currency': 'XCD',
      'flag': '🇲🇸',
    },
    {
      'name': 'Monténégro',
      'code': 'ME',
      'currency': 'EUR',
      'flag': '🇲🇪',
    },
    {
      'name': 'Mozambique',
      'code': 'MZ',
      'currency': 'MZN',
      'flag': '🇲🇿',
    },
    {
      'name': 'Namibie',
      'code': 'NA',
      'currency': 'NAD',
      'flag': '🇳🇦',
    },
    {
      'name': 'Nauru',
      'code': 'NR',
      'currency': 'AUD',
      'flag': '🇳🇷',
    },
    {
      'name': 'Nicaragua',
      'code': 'NI',
      'currency': 'NIO',
      'flag': '🇳🇮',
    },
    {
      'name': 'Niger',
      'code': 'NE',
      'currency': 'XOF',
      'flag': '🇳🇪',
    },
    {
      'name': 'Nigéria',
      'code': 'NG',
      'currency': 'NGN',
      'flag': '🇳🇬',
    },
    {
      'name': 'Niue',
      'code': 'NU',
      'currency': 'NZD',
      'flag': '🇳🇺',
    },
    {
      'name': 'Norvège',
      'code': 'NO',
      'currency': 'NOK',
      'flag': '🇳🇴',
    },
    {
      'name': 'Nouvelle-Calédonie',
      'code': 'NC',
      'currency': 'XPF',
      'flag': '🇳🇨',
    },
    {
      'name': 'Nouvelle-Zélande',
      'code': 'NZ',
      'currency': 'NZD',
      'flag': '🇳🇿',
    },
    {
      'name': 'Népal',
      'code': 'NP',
      'currency': 'NPR',
      'flag': '🇳🇵',
    },
    {
      'name': 'Oman',
      'code': 'OM',
      'currency': 'OMR',
      'flag': '🇴🇲',
    },
    {
      'name': 'Ouganda',
      'code': 'UG',
      'currency': 'UGX',
      'flag': '🇺🇬',
    },
    {
      'name': 'Ouzbékistan',
      'code': 'UZ',
      'currency': 'UZS',
      'flag': '🇺🇿',
    },
    {
      'name': 'Pakistan',
      'code': 'PK',
      'currency': 'PKR',
      'flag': '🇵🇰',
    },
    {
      'name': 'Palaos (Palau)',
      'code': 'PW',
      'currency': 'USD',
      'flag': '🇵🇼',
    },
    {
      'name': 'Palestine',
      'code': 'PS',
      'currency': 'EGP',
      'flag': '🇵🇸',
    },
    {
      'name': 'Panama',
      'code': 'PA',
      'currency': 'PAB',
      'flag': '🇵🇦',
    },
    {
      'name': 'Papouasie-Nouvelle-Guinée',
      'code': 'PG',
      'currency': 'PGK',
      'flag': '🇵🇬',
    },
    {
      'name': 'Paraguay',
      'code': 'PY',
      'currency': 'PYG',
      'flag': '🇵🇾',
    },
    {
      'name': 'Pays-Bas',
      'code': 'NL',
      'currency': 'EUR',
      'flag': '🇳🇱',
    },
    {
      'name': 'Pays-Bas caribéens',
      'code': 'BQ',
      'currency': 'USD',
      'flag': '',
    },
    {
      'name': 'Philippines',
      'code': 'PH',
      'currency': 'PHP',
      'flag': '🇵🇭',
    },
    {
      'name': 'Pologne',
      'code': 'PL',
      'currency': 'PLN',
      'flag': '🇵🇱',
    },
    {
      'name': 'Polynésie française',
      'code': 'PF',
      'currency': 'XPF',
      'flag': '🇵🇫',
    },
    {
      'name': 'Porto Rico',
      'code': 'PR',
      'currency': 'USD',
      'flag': '🇵🇷',
    },
    {
      'name': 'Portugal',
      'code': 'PT',
      'currency': 'EUR',
      'flag': '🇵🇹',
    },
    {
      'name': 'Pérou',
      'code': 'PE',
      'currency': 'PEN',
      'flag': '🇵🇪',
    },
    {
      'name': 'Qatar',
      'code': 'QA',
      'currency': 'QAR',
      'flag': '🇶🇦',
    },
    {
      'name': 'Roumanie',
      'code': 'RO',
      'currency': 'RON',
      'flag': '🇷🇴',
    },
    {
      'name': 'Royaume-Uni',
      'code': 'GB',
      'currency': 'GBP',
      'flag': '🇬🇧',
    },
    {
      'name': 'Russie',
      'code': 'RU',
      'currency': 'RUB',
      'flag': '🇷🇺',
    },
    {
      'name': 'Rwanda',
      'code': 'RW',
      'currency': 'RWF',
      'flag': '🇷🇼',
    },
    {
      'name': 'République centrafricaine',
      'code': 'CF',
      'currency': 'XAF',
      'flag': '🇨🇫',
    },
    {
      'name': 'République dominicaine',
      'code': 'DO',
      'currency': 'DOP',
      'flag': '🇩🇴',
    },
    {
      'name': 'Réunion',
      'code': 'RE',
      'currency': 'EUR',
      'flag': '🇷🇪',
    },
    {
      'name': 'Sahara Occidental',
      'code': 'EH',
      'currency': 'DZD',
      'flag': '🇪🇭',
    },
    {
      'name': 'Saint-Barthélemy',
      'code': 'BL',
      'currency': 'EUR',
      'flag': '🇧🇱',
    },
    {
      'name': 'Saint-Christophe-et-Niévès',
      'code': 'KN',
      'currency': 'XCD',
      'flag': '🇰🇳',
    },
    {
      'name': 'Saint-Marin',
      'code': 'SM',
      'currency': 'EUR',
      'flag': '🇸🇲',
    },
    {
      'name': 'Saint-Martin',
      'code': 'MF',
      'currency': 'EUR',
      'flag': '🇲🇫',
    },
    {
      'name': 'Saint-Martin',
      'code': 'SX',
      'currency': 'ANG',
      'flag': '🇸🇽',
    },
    {
      'name': 'Saint-Pierre-et-Miquelon',
      'code': 'PM',
      'currency': 'EUR',
      'flag': '🇵🇲',
    },
    {
      'name': 'Saint-Vincent-et-les-Grenadines',
      'code': 'VC',
      'currency': 'XCD',
      'flag': '🇻🇨',
    },
    {
      'name': 'Sainte-Hélène, Ascension et Tristan da Cunha',
      'code': 'SH',
      'currency': 'GBP',
      'flag': '🇸🇭',
    },
    {
      'name': 'Sainte-Lucie',
      'code': 'LC',
      'currency': 'XCD',
      'flag': '🇱🇨',
    },
    {
      'name': 'Salvador',
      'code': 'SV',
      'currency': 'USD',
      'flag': '🇸🇻',
    },
    {
      'name': 'Samoa',
      'code': 'WS',
      'currency': 'WST',
      'flag': '🇼🇸',
    },
    {
      'name': 'Samoa américaines',
      'code': 'AS',
      'currency': 'USD',
      'flag': '🇦🇸',
    },
    {
      'name': 'Serbie',
      'code': 'RS',
      'currency': 'RSD',
      'flag': '🇷🇸',
    },
    {
      'name': 'Seychelles',
      'code': 'SC',
      'currency': 'SCR',
      'flag': '🇸🇨',
    },
    {
      'name': 'Sierra Leone',
      'code': 'SL',
      'currency': 'SLL',
      'flag': '🇸🇱',
    },
    {
      'name': 'Singapour',
      'code': 'SG',
      'currency': 'SGD',
      'flag': '🇸🇬',
    },
    {
      'name': 'Slovaquie',
      'code': 'SK',
      'currency': 'EUR',
      'flag': '🇸🇰',
    },
    {
      'name': 'Slovénie',
      'code': 'SI',
      'currency': 'EUR',
      'flag': '🇸🇮',
    },
    {
      'name': 'Somalie',
      'code': 'SO',
      'currency': 'SOS',
      'flag': '🇸🇴',
    },
    {
      'name': 'Soudan',
      'code': 'SD',
      'currency': 'SDG',
      'flag': '🇸🇩',
    },
    {
      'name': 'Soudan du Sud',
      'code': 'SS',
      'currency': 'SSP',
      'flag': '🇸🇸',
    },
    {
      'name': 'Sri Lanka',
      'code': 'LK',
      'currency': 'LKR',
      'flag': '🇱🇰',
    },
    {
      'name': 'Suisse',
      'code': 'CH',
      'currency': 'CHF',
      'flag': '🇨🇭',
    },
    {
      'name': 'Surinam',
      'code': 'SR',
      'currency': 'SRD',
      'flag': '🇸🇷',
    },
    {
      'name': 'Suède',
      'code': 'SE',
      'currency': 'SEK',
      'flag': '🇸🇪',
    },
    {
      'name': 'Svalbard et Jan Mayen',
      'code': 'SJ',
      'currency': 'NOK',
      'flag': '🇸🇯',
    },
    {
      'name': 'Syrie',
      'code': 'SY',
      'currency': 'SYP',
      'flag': '🇸🇾',
    },
    {
      'name': 'São Tomé et Príncipe',
      'code': 'ST',
      'currency': 'STN',
      'flag': '🇸🇹',
    },
    {
      'name': 'Sénégal',
      'code': 'SN',
      'currency': 'XOF',
      'flag': '🇸🇳',
    },
    {
      'name': 'Tadjikistan',
      'code': 'TJ',
      'currency': 'TJS',
      'flag': '🇹🇯',
    },
    {
      'name': 'Tanzanie',
      'code': 'TZ',
      'currency': 'TZS',
      'flag': '🇹🇿',
    },
    {
      'name': 'Taïwan',
      'code': 'TW',
      'currency': 'TWD',
      'flag': '🇹🇼',
    },
    {
      'name': 'Tchad',
      'code': 'TD',
      'currency': 'XAF',
      'flag': '🇹🇩',
    },
    {
      'name': 'Tchéquie',
      'code': 'CZ',
      'currency': 'CZK',
      'flag': '🇨🇿',
    },
    {
      'name': 'Terres australes et antarctiques françaises',
      'code': 'TF',
      'currency': 'EUR',
      'flag': '🇹🇫',
    },
    {
      'name': 'Territoire britannique de l\'océan Indien',
      'code': 'IO',
      'currency': 'USD',
      'flag': '🇮🇴',
    },
    {
      'name': 'Thaïlande',
      'code': 'TH',
      'currency': 'THB',
      'flag': '🇹🇭',
    },
    {
      'name': 'Timor oriental',
      'code': 'TL',
      'currency': 'USD',
      'flag': '🇹🇱',
    },
    {
      'name': 'Togo',
      'code': 'TG',
      'currency': 'XOF',
      'flag': '🇹🇬',
    },
    {
      'name': 'Tokelau',
      'code': 'TK',
      'currency': 'NZD',
      'flag': '🇹🇰',
    },
    {
      'name': 'Tonga',
      'code': 'TO',
      'currency': 'TOP',
      'flag': '🇹🇴',
    },
    {
      'name': 'Trinité-et-Tobago',
      'code': 'TT',
      'currency': 'TTD',
      'flag': '🇹🇹',
    },
    {
      'name': 'Tunisie',
      'code': 'TN',
      'currency': 'TND',
      'flag': '🇹🇳',
    },
    {
      'name': 'Turkménistan',
      'code': 'TM',
      'currency': 'TMT',
      'flag': '🇹🇲',
    },
    {
      'name': 'Turquie',
      'code': 'TR',
      'currency': 'TRY',
      'flag': '🇹🇷',
    },
    {
      'name': 'Tuvalu',
      'code': 'TV',
      'currency': 'AUD',
      'flag': '🇹🇻',
    },
    {
      'name': 'Ukraine',
      'code': 'UA',
      'currency': 'UAH',
      'flag': '🇺🇦',
    },
    {
      'name': 'Uruguay',
      'code': 'UY',
      'currency': 'UYU',
      'flag': '🇺🇾',
    },
    {
      'name': 'Vanuatu',
      'code': 'VU',
      'currency': 'VUV',
      'flag': '🇻🇺',
    },
    {
      'name': 'Venezuela',
      'code': 'VE',
      'currency': 'VES',
      'flag': '🇻🇪',
    },
    {
      'name': 'Viêt Nam',
      'code': 'VN',
      'currency': 'VND',
      'flag': '🇻🇳',
    },
    {
      'name': 'Wallis-et-Futuna',
      'code': 'WF',
      'currency': 'XPF',
      'flag': '🇼🇫',
    },
    {
      'name': 'Yémen',
      'code': 'YE',
      'currency': 'YER',
      'flag': '🇾🇪',
    },
    {
      'name': 'Zambie',
      'code': 'ZM',
      'currency': 'ZMW',
      'flag': '🇿🇲',
    },
    {
      'name': 'Zimbabwe',
      'code': 'ZW',
      'currency': 'BWP',
      'flag': '🇿🇼',
    },
    {
      'name': 'Égypte',
      'code': 'EG',
      'currency': 'EGP',
      'flag': '🇪🇬',
    },
    {
      'name': 'Émirats arabes unis',
      'code': 'AE',
      'currency': 'AED',
      'flag': '🇦🇪',
    },
    {
      'name': 'Équateur',
      'code': 'EC',
      'currency': 'USD',
      'flag': '🇪🇨',
    },
    {
      'name': 'Érythrée',
      'code': 'ER',
      'currency': 'ERN',
      'flag': '🇪🇷',
    },
    {
      'name': 'États-Unis',
      'code': 'US',
      'currency': 'USD',
      'flag': '🇺🇸',
    },
    {
      'name': 'Éthiopie',
      'code': 'ET',
      'currency': 'ETB',
      'flag': '🇪🇹',
    },
    {
      'name': 'Île Bouvet',
      'code': 'BV',
      'currency': '',
      'flag': '🇧🇻',
    },
    {
      'name': 'Île Christmas',
      'code': 'CX',
      'currency': 'AUD',
      'flag': '🇨🇽',
    },
    {
      'name': 'Île Maurice',
      'code': 'MU',
      'currency': 'MUR',
      'flag': '🇲🇺',
    },
    {
      'name': 'Île Norfolk',
      'code': 'NF',
      'currency': 'AUD',
      'flag': '🇳🇫',
    },
    {
      'name': 'Île de Man',
      'code': 'IM',
      'currency': 'GBP',
      'flag': '🇮🇲',
    },
    {
      'name': 'Îles Caïmans',
      'code': 'KY',
      'currency': 'KYD',
      'flag': '🇰🇾',
    },
    {
      'name': 'Îles Cocos',
      'code': 'CC',
      'currency': 'AUD',
      'flag': '🇨🇨',
    },
    {
      'name': 'Îles Cook',
      'code': 'CK',
      'currency': 'CKD',
      'flag': '🇨🇰',
    },
    {
      'name': 'Îles Féroé',
      'code': 'FO',
      'currency': 'DKK',
      'flag': '🇫🇴',
    },
    {
      'name': 'Îles Heard-et-MacDonald',
      'code': 'HM',
      'currency': '',
      'flag': '🇭🇲',
    },
    {
      'name': 'Îles Malouines',
      'code': 'FK',
      'currency': 'FKP',
      'flag': '🇫🇰',
    },
    {
      'name': 'Îles Mariannes du Nord',
      'code': 'MP',
      'currency': 'USD',
      'flag': '🇲🇵',
    },
    {
      'name': 'Îles Marshall',
      'code': 'MH',
      'currency': 'USD',
      'flag': '🇲🇭',
    },
    {
      'name': 'Îles Pitcairn',
      'code': 'PN',
      'currency': 'NZD',
      'flag': '🇵🇳',
    },
    {
      'name': 'Îles Salomon',
      'code': 'SB',
      'currency': 'SBD',
      'flag': '🇸🇧',
    },
    {
      'name': 'Îles Turques-et-Caïques',
      'code': 'TC',
      'currency': 'USD',
      'flag': '🇹🇨',
    },
    {
      'name': 'Îles Vierges britanniques',
      'code': 'VG',
      'currency': 'USD',
      'flag': '🇻🇬',
    },
    {
      'name': 'Îles Vierges des États-Unis',
      'code': 'VI',
      'currency': 'USD',
      'flag': '🇻🇮',
    },
    {
      'name': 'Îles du Cap-Vert',
      'code': 'CV',
      'currency': 'CVE',
      'flag': '🇨🇻',
    },
    {
      'name': 'Îles mineures éloignées des États-Unis',
      'code': 'UM',
      'currency': 'USD',
      'flag': '🇺🇲',
    },
  ];
}